version: '3.4'

services:
  nginx:
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./data:/data    
      - ./data/nginx/etc/nginx:/etc/nginx
      - ./data/certbot/etc/letsencrypt:/etc/letsencrypt
      - ./data/shared/var/www/static:/var/www/static
    build:
      context: .
      dockerfile: proxy/Dockerfile
    ports:
      - "80:80"
      - "443:443"
      - "8200:8200"
    links:
      - vault
    entrypoint: /bin/sh -c /data/nginx.entrypoint.sh
  certbot:
    container_name: cerbot
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./data/certbot/etc/letsencrypt:/etc/letsencrypt
      - ./data/shared/var/www/static:/var/www/static
    depends_on: 
      - nginx
    entrypoint: /bin/sh -c /data/certbot.entrypoint.sh
  vault:
    image: vault
    container_name: vault
    restart: always
    volumes:
      - ./data/vault/certs:/vault/certs
      - ./data/vault/logs:/vault/logs
      - ./data/vault/file:/vault/file
      - ./data/vault/config:/vault/config
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json
